IF OBJECT_ID(N'dbo.USER_ROLE', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[USER_ROLE]
    (
        Id        BIGINT PRIMARY KEY IDENTITY(1, 1),
        UserId    BIGINT NOT NULL,
        RoleId    BIGINT NOT NULL,
        CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        DeletedAt DATETIME2 NULL,

        CONSTRAINT FK_USER_ROLE_User FOREIGN KEY (UserId)
        REFERENCES [dbo].[USER](Id) ON DELETE CASCADE,

        CONSTRAINT FK_USER_ROLE_Role FOREIGN KEY (RoleId)
        REFERENCES [dbo].[ROLE](Id) ON DELETE CASCADE
    );
END;