IF OBJECT_ID(N'dbo.ROLE_PERMISSION', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[ROLE_PERMISSION]
    (
        Id           BIGINT PRIMARY KEY IDENTITY(1, 1),
        RoleId       BIGINT NOT NULL,
        PermissionId BIGINT NOT NULL,
        CreatedAt    DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        DeletedAt    DATETIME2 NULL,

        CONSTRAINT FK_ROLE_PERMISSION_Role FOREIGN KEY (RoleId)
        REFERENCES [dbo].[ROLE](Id) ON DELETE CASCADE,

        CONSTRAINT FK_ROLE_PERMISSION_Permission FOREIGN KEY (PermissionId)
        REFERENCES [dbo].[PERMISSION](Id) ON DELETE CASCADE
    );
END;